name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build-package:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Restore Packages
      run: nuget restore PullZoom.sln
    - name: Compile Package
      working-directory: PullZoom
      run: dotnet pack PullZoom.csproj -c Release
    - uses: actions/upload-artifact@v3
      with:
        name: uvaPullZoom
        path: PullZoom/bin/Release/PullZoom*.nupkg
  build-docs:
 
   runs-on: ubuntu-latest
   
   steps:
   - name: Install doxygen
     run: sudo apt-get install -y doxygen graphviz
   - name: Checkout
     uses: actions/checkout@v2
   - name: Run doxygen
     run: doxygen PullZoom/Doxyfile
   - name: Deploy docs
     uses: peaceiris/actions-gh-pages@v3
     with:
       github_token: ${{secrets.GITHUB_TOKEN}}
       publish_dir: docs/html

  deploy-package:
  
    runs-on: ubuntu-latest
    needs: build-package
    
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: uvaPullZoom
    - name: Run deploy script
      run: curl -vX PUT -u "uvadev:${{secrets.GITHUB_TOKEN}}" -F package="@$(echo PullZoom.*.nupkg)" https://nuget.pkg.github.com/uvadev/
      shell: bash
